export const actionsEnums = {
      HTTP_GET_CALL_STARTED: 'HTTP_GET_CALL_STARTED',
      HTTP_GET_CALL_COMPLETED: 'HTTP_GET_CALL_COMPLETED',
      MEMBERS_REQUEST_COMPLETED: 'MEMBER_REQUEST_COMPLETED',
      HTTP_INITIALIZE_DISPATCHER: 'HTTP_INITIALIZE_DISPATCHER'
}
