export const actionsEnums = {
     common : {
       HTTP_GET_CALL_STARTED: 'COMMON_HTTP_GET_CALL_STARTED',
       HTTP_GET_CALL_COMPLETED: 'COMMON_HTTP_GET_CALL_COMPLETED',
       HTTP_INITIALIZE_DISPATCHER: 'COMMON_HTTP_INITIALIZE_DISPATCHER'
     },
     membersPage: {
       MEMBERS_REQUEST_COMPLETED: 'MEMBERS_PAGE_MEMBER_REQUEST_COMPLETED',
     },
     memberPage: {
        MEMBER_INITIALIZE_NEW: 'MEMBER_PAGE_MEMBER_INITIALIZE_NEW',
        MEMBER_LOAD: 'MEMBER_PAGE_MEMBER_LOAD',
        MEMBER_RESET_SAVE_COMPLETED: 'MEMBER_PAGE_MEMBER_RESET_SAVE_COMPLETED',
        MEMBER_SAVE: 'MEMBER_PAGE_MEMBER_SAVE',
        MEMBER_UI_INPUT: 'MEMBER_PAGE_MEMBER_UI_INPUT'
     }
}
